
	(callback => {
		if (document.readyState != 'loading') callback();
		else document.addEventListener('DOMContentLoaded', callback);
	})(() => {
		
		const body=document.getElementsByTagName('body');
		


		var element2 = document.createElement("div");
		element2.innerHTML=`
		<div style='color:purple;'>
		This text was generated by a script tag served from js-lightning.
		</div>`;

		document.body.appendChild(element2);

	});

